"""Numeric snapshot tests for the three vetrina examples.

For each model (msd, cs, fbl) two layers of fingerprints are checked:

* **Static fingerprint** (rtol = 1e-12, atol = 1e-12) -- the constant
  matrices and the t = 0 evaluation of ``Phi_q``, ``gamma`` and ``Q``.
* **Dynamic fingerprint** (rtol = 1e-9, atol = 1e-12) -- 11 decile samples
  from ``T`` and the corresponding rows of ``uT``, checked once per
  solver (LSODA and CASADI-DAE).

Reference data live in ``tests/numeric_refs/<model>_static.npz`` and
``tests/numeric_refs/<model>_<solver>.npz`` and are regenerated by
``tests/_regen_refs.py``.

The test suite is fast because the dynamic check just runs ``solve`` for
each (model, solver) once and samples 11 points -- no expensive output
post-processing.
"""
from __future__ import annotations

import importlib
import sys
from pathlib import Path

import numpy as np
import pytest


# ---------------------------------------------------------------------------
# Paths and registry
# ---------------------------------------------------------------------------
HERE = Path(__file__).resolve().parent
PMD_ROOT = HERE.parent
REFS_DIR = HERE / "numeric_refs"

if str(PMD_ROOT) not in sys.path:
    sys.path.insert(0, str(PMD_ROOT))

MODELS: dict[str, str] = {
    "msd": "examples.mass_spring_damper",
    "cs":  "examples.crank_slider",
    "fbl": "examples.four_bar_linkage",
}

SOLVERS: dict[str, str] = {
    "lsoda":  "LSODA",
    "casadi": "CASADI-DAE",
}

N_SAMPLES = 11

# Tolerances (decision #1 of work-stream C plan).
RTOL_STATIC,  ATOL_STATIC  = 1e-12, 1e-12
RTOL_DYNAMIC, ATOL_DYNAMIC = 1e-9,  1e-12


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _fresh_build(model_key: str):
    """Re-import the example module to avoid leaked Body/Joint counters."""
    module_name = MODELS[model_key]
    if module_name in sys.modules:
        del sys.modules[module_name]
    return importlib.import_module(module_name)


def _decile_indices(n: int) -> np.ndarray:
    return np.linspace(0, n - 1, N_SAMPLES).astype(int)


# ---------------------------------------------------------------------------
# Static fingerprint
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("model_key", sorted(MODELS))
def test_static_fingerprint(model_key: str) -> None:
    """Mass matrix + t=0 constraint Jacobian / gamma / forces match reference."""
    mod = _fresh_build(model_key)
    model = mod.build_model()
    model.t = 0.0

    q0    = model._bodies2u()
    M     = model.M_matrix
    Phi_q = model._compute_jacobian()
    gamma = model._rhs_acceleration()
    Q     = model._compute_force()

    ref = np.load(REFS_DIR / f"{model_key}_static.npz")
    np.testing.assert_allclose(q0,    ref["q0"],    rtol=RTOL_STATIC, atol=ATOL_STATIC,
                               err_msg=f"{model_key}: q0 mismatch")
    np.testing.assert_allclose(M,     ref["M"],     rtol=RTOL_STATIC, atol=ATOL_STATIC,
                               err_msg=f"{model_key}: M mismatch")
    np.testing.assert_allclose(Phi_q, ref["Phi_q"], rtol=RTOL_STATIC, atol=ATOL_STATIC,
                               err_msg=f"{model_key}: Phi_q mismatch")
    np.testing.assert_allclose(gamma, ref["gamma"], rtol=RTOL_STATIC, atol=ATOL_STATIC,
                               err_msg=f"{model_key}: gamma mismatch")
    np.testing.assert_allclose(Q,     ref["Q"],     rtol=RTOL_STATIC, atol=ATOL_STATIC,
                               err_msg=f"{model_key}: Q mismatch")


# ---------------------------------------------------------------------------
# Dynamic fingerprint (one test per (model, solver) pair)
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "model_key,solver_key",
    [(m, s) for m in sorted(MODELS) for s in sorted(SOLVERS)],
)
def test_dynamic_fingerprint(model_key: str, solver_key: str) -> None:
    """11 decile samples of (T, uT) match the per-solver reference."""
    mod = _fresh_build(model_key)
    model = mod.build_model()

    T, uT = model.solve(
        method=SOLVERS[solver_key],
        t_final=mod.T_FINAL,
        t_eval=np.linspace(0.0, mod.T_FINAL, mod.N_EVAL),
        ic_correct=mod.IC_CORRECT,
    )
    idx = _decile_indices(len(T))
    t_samples = T[idx]
    u_samples = uT[idx, :]

    ref = np.load(REFS_DIR / f"{model_key}_{solver_key}.npz")
    np.testing.assert_allclose(t_samples, ref["t_samples"],
                               rtol=RTOL_DYNAMIC, atol=ATOL_DYNAMIC,
                               err_msg=f"{model_key}/{solver_key}: t_samples mismatch")
    np.testing.assert_allclose(u_samples, ref["u_samples"],
                               rtol=RTOL_DYNAMIC, atol=ATOL_DYNAMIC,
                               err_msg=f"{model_key}/{solver_key}: u_samples mismatch")
